/**
 * @module BarrelWriter
 *
 * Pure codegen — zero LLM calls. Writes (or updates) an `index.mjs` barrel
 * file that re-exports every compiled unit from its individual file.
 *
 * The barrel is the only file consumers import; unit files are treated as
 * internal implementation details.
 *
 * Example output for units [formatRelativeTime, formatShortDate, isToday]:
 *
 *   // AUTO-GENERATED — do not edit by hand. Re-run the decomposer to update.
 *   export { formatRelativeTime } from './formatRelativeTime.mjs';
 *   export { formatShortDate } from './formatShortDate.mjs';
 *   export { isToday } from './isToday.mjs';
 */

import fs from 'node:fs';
import path from 'node:path';

/** @typedef {import('./UnitExtractor.mjs').UnitDescriptor} UnitDescriptor */

export class BarrelWriter {
    /**
     * @param {object} opts
     * @param {string} opts.outDir - Abs path to the directory containing unit files.
     */
    constructor({ outDir }) {
        this.outDir = outDir;
    }

    /**
     * Write `index.mjs` into `outDir` that re-exports all successfully compiled units.
     *
     * @param {UnitDescriptor[]} units     - Full unit list (provides names + kinds).
     * @param {Set<string>}      succeeded - Names of units that actually compiled (others skipped).
     * @returns {string} Abs path to the written barrel file.
     */
    write(units, succeeded) {
        const barrelPath = path.join(this.outDir, 'index.mjs');

        const exportLines = units
            .filter(u => succeeded.has(u.name))
            .map(u => `export { ${u.name} } from './${u.name}.mjs';`);

        if (exportLines.length === 0) {
            console.warn('[BarrelWriter] No succeeded units — writing empty barrel.');
        }

        const banner = [
            '// AUTO-GENERATED by Waymark decomposer — do not edit by hand.',
            '// Re-run `node src/compiler/decomposer/run.mjs` to regenerate.',
            '',
        ].join('\n');

        const content = banner + exportLines.join('\n') + '\n';

        fs.mkdirSync(this.outDir, { recursive: true });
        fs.writeFileSync(barrelPath, content, 'utf-8');

        console.log(`[BarrelWriter] Wrote barrel: ${barrelPath}`);
        console.log(`              Exports: ${exportLines.length} unit(s)`);

        return barrelPath;
    }

    /**
     * Read an existing barrel and return the set of already-exported names.
     * Useful for incremental runs — skip recompiling what's already clean.
     *
     * @returns {Set<string>}
     */
    readExisting() {
        const barrelPath = path.join(this.outDir, 'index.mjs');
        if (!fs.existsSync(barrelPath)) return new Set();

        const source = fs.readFileSync(barrelPath, 'utf-8');
        const names = new Set();

        // Match lines: export { <name> } from './<name>.mjs';
        const lineRe = /^export\s*\{\s*(\w+)\s*\}\s*from\s*'\.\/\1\.mjs';/gm;
        let m;
        while ((m = lineRe.exec(source)) !== null) {
            names.add(m[1]);
        }

        return names;
    }
}
