/**
 * @module IntegrationSmokeWriter
 *
 * Post-DAG safety net. After all units in a decompose stage succeed their
 * individual Vitest unit tests (which use contract-derived vi.mock() stubs),
 * this writer generates a smoke test that imports REAL compiled units.
 *
 * This is what catches "the mock matched the contract but the compiled
 * implementation diverged at runtime."
 *
 * What the smoke test does:
 *   1. Imports every succeeded unit from the barrel (index.mjs).
 *   2. For every dep edge in the DAG (A → B means B depends on A), exercises
 *      a boundary call: calls B with output from A's documented return shape.
 *   3. Asserts no exceptions are thrown across the boundary.
 *   4. Does NOT assert business logic — that's the unit tests' job.
 *      It only asserts "these real modules can talk to each other without
 *      blowing up."
 *
 * The smoke test is generated by Gemini but with a strict constraint:
 *   - Import ONLY from the barrel (index.mjs) — never from unit files directly.
 *   - No mocks. vi.mock() is forbidden.
 *   - Assertions are structural (typeof, instanceof, no-throw) not logical.
 *
 * Output: `<outDir>/integration.smoke.test.mjs`
 */

import fs from 'node:fs';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

export class IntegrationSmokeWriter {
    /**
     * @param {object} opts
     * @param {string} opts.outDir - Abs path to the directory containing unit files + barrel.
     */
    constructor({ outDir }) {
        this.outDir = outDir;
    }

    /**
     * Generate and write the integration smoke test.
     *
     * @param {import('./UnitExtractor.mjs').UnitDescriptor[]} units   - All units.
     * @param {Set<string>} succeeded   - Names of units that compiled successfully.
     * @returns {Promise<string>} Abs path to the written smoke test file.
     */
    async write(units, succeeded) {
        const smokePath = path.join(this.outDir, 'integration.smoke.test.mjs');
        const barrelPath = path.join(this.outDir, 'index.mjs');

        // Filter to succeeded units only — no point testing failed ones.
        const liveUnits = units.filter(u => succeeded.has(u.name));

        if (liveUnits.length === 0) {
            console.warn('[IntegrationSmokeWriter] No succeeded units — skipping smoke test generation.');
            return smokePath;
        }

        // ── Build dep edge list for the prompt ───────────────────────────────
        const depEdges = [];
        for (const unit of liveUnits) {
            for (const dep of unit.deps) {
                if (succeeded.has(dep)) {
                    depEdges.push(`${dep} → ${unit.name}`);
                }
            }
        }

        // ── Build function call hints based on UnitDescriptor params ─────────
        const callHints = liveUnits
            .filter(u => u.kind === 'function')
            .map(u => {
                const args = u.params.map(p => this.#inferArgValue(p)).join(', ');
                return `  ${u.name}(${args}) — check: no-throw, returns non-undefined`;
            });

        const prompt = [
            'You are a test engineer writing an integration smoke test.',
            '',
            'Write a vitest smoke test that validates real compiled units can',
            'interact across their dependency boundaries without throwing.',
            '',
            `Units in this module (all compiled successfully):`,
            ...liveUnits.map(u => `  - ${u.name} (${u.kind}, params: ${u.params.join(', ') || 'none'})`),
            '',
            depEdges.length > 0
                ? `Dependency edges (caller depends on callee):\n${depEdges.map(e => `  ${e}`).join('\n')}`
                : 'No inter-unit dependencies.',
            '',
            'Suggested call patterns to exercise:',
            ...callHints,
            '',
            'STRICT RULES:',
            `  1. Import ALL units from './index.mjs' (the barrel). NEVER import unit files directly.`,
            `  2. NO vi.mock(). NO fake data. Use real inputs with reasonable values.`,
            `  3. Assertions must be structural only:`,
            `       - expect(() => fn(...args)).not.toThrow()`,
            `       - expect(result).toBeDefined()`,
            `       - expect(typeof result).toBe('string' | 'number' | 'boolean' | 'object')`,
            `  4. Do NOT assert specific values or business logic — that is the unit tests' job.`,
            `  5. Wrap every call in a try/catch or use .not.toThrow().`,
            `  6. One describe block named "Integration Smoke" containing all tests.`,
            '',
            'OUTPUT CONSTRAINT: Respond with ONLY the complete test file inside a',
            'single ```javascript code fence. No preamble. No explanation.',
        ].join('\n');

        const { stdout } = await execFileAsync(
            'gemini',
            ['--skip-trust', '--output-format', 'text', '-p', prompt],
            { timeout: 90_000, maxBuffer: 4_194_304 }
        );

        const fence = /```(?:javascript|js)?\n([\s\S]*?)```/.exec(stdout);
        const content = fence ? fence[1] : stdout.trim();

        fs.mkdirSync(this.outDir, { recursive: true });
        fs.writeFileSync(smokePath, content, 'utf-8');

        console.log(`[IntegrationSmokeWriter] Smoke test written: ${smokePath}`);
        console.log(`  Covers ${liveUnits.length} unit(s), ${depEdges.length} boundary edge(s).`);

        return smokePath;
    }

    // ── Private ──────────────────────────────────────────────────────────────

    /**
     * Infer a reasonable default argument value from a parameter name.
     * Keeps the smoke test from passing undefined to everything.
     *
     * @param {string} paramName
     * @returns {string} A JS literal as a string.
     */
    #inferArgValue(paramName) {
        const name = paramName.toLowerCase();

        if (/^(ms|millis|milliseconds|time|timestamp|epoch)$/.test(name)) return 'Date.now()';
        if (/^(date|d|now)$/.test(name)) return 'new Date()';
        if (/^(str|string|text|val|value|s)$/.test(name)) return "'test'";
        if (/^(n|num|number|count|len|length|size|i|index)$/.test(name)) return '1';
        if (/^(bool|flag|enabled|active|visible)$/.test(name)) return 'true';
        if (/^(arr|array|list|items)$/.test(name)) return '[]';
        if (/^(obj|object|opts|options|config|cfg)$/.test(name)) return '{}';
        if (/^(id|uid|uuid)$/.test(name)) return "'test-id'";
        if (/^(url|uri|href|src)$/.test(name)) return "'https://example.com'";
        if (/^(fn|callback|cb|handler)$/.test(name)) return '() => {}';

        // Default: string literal with the param name so it's identifiable in output.
        return `'${paramName}-value'`;
    }
}
