const path = require('path');
const fs = require('fs');
const express = require('express');
const cookieParser = require('cookie-parser');
const config = require('./config');
const setupAuth = require('./auth');
const { createGitHubSource, isValidRef } = require('./github-source');

const app = express();

/* ---------- Git hash + repo URL (baked at build time) ---------- */
// Generated by `node scripts/build-info.js` before `docker build`.
// Falls back to live git commands for local dev when no build-info.json exists.
let gitHash = '';
let gitRepoUrl = '';
try {
  const info = JSON.parse(fs.readFileSync(path.join(__dirname, 'build-info.json'), 'utf-8'));
  gitHash = info.hash || '';
  gitRepoUrl = info.repo || '';
} catch {
  // No build-info.json — try live git (works in dev, not in Docker)
  try {
    const { execSync } = require('child_process');
    gitHash = execSync('git rev-parse --short HEAD', { cwd: __dirname }).toString().trim();
    const remote = execSync('git remote get-url origin', { cwd: __dirname }).toString().trim();
    gitRepoUrl = remote.replace(/^git@github\.com:/, 'https://github.com/').replace(/\.git$/, '');
  } catch { /* not a git repo — hash stays empty */ }
}

/* ---------- Per-user ref resolution ---------- */

/**
 * Determine which GitHub ref to serve for this specific request.
 * Resolution order (per-user, never shared across users):
 *   1. waymark_session_ref signed cookie  — temporary switch (cleared on login/logout)
 *   2. waymark_pinned_ref signed cookie   — persisted user preference
 *   3. config.GITHUB_REF                 — server default
 *
 * cookieParser (signed) must already be applied to req before calling this.
 */
function getRefForRequest(req) {
  const sessionRef = req.signedCookies?.waymark_session_ref;
  if (sessionRef && isValidRef(sessionRef)) return sessionRef;
  const pinnedRef = req.signedCookies?.waymark_pinned_ref;
  if (pinnedRef && isValidRef(pinnedRef)) return pinnedRef;
  return config.GITHUB_REF;
}

/* ---------- Base-path aware router ---------- */
// When BASE_PATH is set (e.g. '/waymark'), all routes are mounted under
// that prefix so the app can live behind an nginx location block.
const basePath = config.BASE_PATH || '';
const router = express.Router();

/* ---------- Top-level middleware (runs before router) ---------- */

app.use(cookieParser(config.COOKIE_SECRET));
app.use(express.json());

// Security headers
app.use((_req, res, next) => {
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('X-Frame-Options', 'DENY');
  res.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin');
  res.setHeader('Permissions-Policy', 'camera=(self), microphone=(self)');

  if (config.NODE_ENV === 'production') {
    res.setHeader(
      'Content-Security-Policy',
      [
        "default-src 'self'",
        "script-src 'self' 'unsafe-inline' https://static.cloudflareinsights.com https://apis.google.com",
        "connect-src 'self' ws://localhost:9001 https://www.googleapis.com https://sheets.googleapis.com https://oauth2.googleapis.com https://drive.googleapis.com https://generativelanguage.googleapis.com",
        "frame-src https://docs.google.com",
        "img-src 'self' https://*.googleusercontent.com https://drive.google.com data:",
        "style-src 'self' 'unsafe-inline'",
      ].join('; ')
    );
  }

  next();
});

/* ---------- GitHub source setup ---------- */
// In production: clone the repo and serve files from a local git checkout.
// In WAYMARK_LOCAL mode: skip the clone, serve from local public/ only.

let githubSource;
if (config.WAYMARK_LOCAL || config.GITHUB_SOURCE_LOCAL) {
  // Stub — serve from local public/ directory (mock mode or local dev override)
  if (config.GITHUB_SOURCE_LOCAL && !config.WAYMARK_LOCAL) {
    console.log('🔧  GITHUB_SOURCE_LOCAL=true — serving frontend from local public/ (auth still live)');
  }
  githubSource = {
    middleware: (_req, _res, next) => next(),
    setRef() {},
    getRef() { return config.GITHUB_REF; },
    getContentShaForRef() { return null; },
    preWarm() {},
    purgeCache() {},
    listCachedRefs() { return []; },
    readFile() { return null; },
  };
} else {
  githubSource = createGitHubSource({
    owner: config.GITHUB_OWNER,
    repo: config.GITHUB_REPO,
    ref: config.GITHUB_REF,
    token: config.GITHUB_TOKEN || undefined,
    resolveRef: getRefForRequest,
  });
  console.log(`📦  GitHub source: ${config.GITHUB_OWNER}/${config.GITHUB_REPO}@${config.GITHUB_REF} (local files as fallback)`);
}

/* ---------- Injection safety ---------- */

/**
 * Escape a value for safe embedding inside an inline <script> block.
 * JSON.stringify handles quotes/backslashes; the replace covers </script>
 * and <!-- sequences that could break out of the script element.
 */
function safeJsString(val) {
  return JSON.stringify(String(val)).replace(/</g, '\\u003c').replace(/>/g, '\\u003e');
}

/* ---------- Helper: serve index.html with injections ---------- */

// Per-ref in-memory HTML cache.
// Each user's ref gets its own entry, keyed by ref string, so one user
// switching refs NEVER invalidates or replaces another user's cached HTML.
// Never used in local mode where source files change during development.
const _htmlCacheByRef = new Map();

function serveIndex(req, res) {
  // Determine the ref for THIS specific user's request.
  const currentRef = config.WAYMARK_LOCAL ? config.GITHUB_REF : getRefForRequest(req);

  // Serve from per-ref in-memory cache when the content SHA hasn't changed.
  if (!config.WAYMARK_LOCAL) {
    const sha = githubSource.getContentShaForRef(currentRef);
    const cached = _htmlCacheByRef.get(currentRef);
    if (sha && cached && sha === cached.sha) {
      res.setHeader('Cache-Control', 'no-cache, must-revalidate');
      if (gitHash) res.setHeader('X-Waymark-Hash', gitHash);
      return res.type('html').send(cached.html);
    }
  }
  // Read index.html from the git checkout for this user's ref, fall back to local file
  let html = githubSource.readFile('index.html', currentRef);
  if (!html) {
    const htmlPath = path.join(__dirname, '..', 'public', 'index.html');
    html = fs.readFileSync(htmlPath, 'utf-8');
  }

  // Inject runtime flags — all values are escaped to prevent XSS
  const injections = [];
  if (basePath) {
    injections.push(`window.__WAYMARK_BASE=${safeJsString(basePath)};`);
  }
  if (config.WAYMARK_LOCAL) {
    injections.push('window.__WAYMARK_LOCAL=true;');
  }
  if (gitHash) {
    injections.push(`window.__WAYMARK_HASH=${safeJsString(gitHash)};`);
  }
  if (gitRepoUrl) {
    injections.push(`window.__WAYMARK_REPO=${safeJsString(gitRepoUrl)};`);
  }
  if (!config.WAYMARK_LOCAL) {
    injections.push(`window.__WAYMARK_GITHUB_REF=${safeJsString(currentRef)};`);
  }
  // Extract GCP project number from client ID (prefix before first dash)
  const gcpProject = (config.GOOGLE_CLIENT_ID || '').split('-')[0];
  if (gcpProject) {
    injections.push(`window.__WAYMARK_GCP_PROJECT=${safeJsString(gcpProject)};`);
  }
  if (config.GOOGLE_API_KEY) {
    injections.push(`window.__WAYMARK_API_KEY=${safeJsString(config.GOOGLE_API_KEY)};`);
  }
  if (injections.length) {
    html = html.replace('</head>', `  <script>${injections.join('')}</script>\n</head>`);
  }

  // In production mode, inject a ref-switcher into the settings modal.
  // This is the ONLY mechanism for version switching — no frontend code
  // should auto-switch refs.  The injected script runs as a regular <script>
  // before any <script type="module"> (app.js), so it can set localStorage
  // first to prevent stale boot-time sync code in old branches.
  if (!config.WAYMARK_LOCAL) {
    html = html.replace('</body>', `${buildSettingsRefInjector(currentRef)}\n</body>`);
  }

  // Store in per-ref cache so this user's HTML doesn't pollute other users' entries.
  if (!config.WAYMARK_LOCAL) {
    const sha = githubSource.getContentShaForRef(currentRef);
    if (sha) _htmlCacheByRef.set(currentRef, { sha, html });
  }

  // Vary: Cookie ensures any caching layer (proxy, CDN) keys responses
  // on the user's cookies — preventing User A's ref from being served to User B.
  res.setHeader('Vary', 'Cookie');
  res.setHeader('Cache-Control', 'no-cache, must-revalidate');
  if (gitHash) res.setHeader('X-Waymark-Hash', gitHash);
  res.type('html').send(html);
}

/* ---------- Server-injected settings version section ---------- */

/**
 * Build a self-contained <script> that:
 * 1. Immediately syncs localStorage to match the server's ref (prevents
 *    stale boot-time sync in old branches)
 * 2. When the settings modal opens, injects a version section with:
 *    - Input + Switch button (temporary preview)
 *    - Pin button (persists via Google Drive + cookie cache)
 *    - Quick-switch tag buttons for cached refs
 *    - Current/pinned ref display
 * 3. On switch: POSTs to /api/source/ref, sets sessionStorage flag, reloads
 * 4. On pin:    POSTs to /api/source/pin (cookie cache), saves to Drive
 *              via window.__waymarkSavePinnedRef(), reloads
 */
function buildSettingsRefInjector(currentRef) {
  const safeRef = safeJsString(currentRef);
  return `
<script>
(function() {
  var BASE = window.__WAYMARK_BASE || '';
  var CURRENT_REF = ${safeRef};

  // Sync localStorage immediately (before type=module scripts run)
  try { localStorage.setItem('waymark_github_ref', JSON.stringify(CURRENT_REF)); } catch(e) {}

  var injected = false;
  var obs = new MutationObserver(function() {
    var modal = document.getElementById('settings-modal');
    if (!modal || modal.classList.contains('hidden')) return;
    if (injected) return;
    inject(modal);
  });
  obs.observe(document.body, { attributes: true, subtree: true, attributeFilter: ['class'] });

  function inject(modal) {
    injected = true;

    // Hide native version section
    var native = document.getElementById('settings-version-section');
    if (native) native.style.display = 'none';
    if (document.getElementById('wm-ver')) return;

    var footer = modal.querySelector('.modal-footer');
    if (!footer) return;

    var s = document.createElement('div');
    s.id = 'wm-ver';
    s.className = 'settings-section';
    s.innerHTML =
      '<h4 class="settings-section-title">App Version</h4>' +
      '<div class="settings-row">' +
        '<span class="settings-label">Branch / Ref</span>' +
        '<div style="display:flex;gap:6px;align-items:center;flex-wrap:wrap;">' +
          '<input id="wm-ref" type="text" value="' + CURRENT_REF + '" ' +
            'placeholder="main" autocomplete="off" spellcheck="false" ' +
            'style="padding:6px 10px;border-radius:6px;border:1px solid var(--color-border,#e2e8f0);' +
            'background:var(--color-surface,#fff);color:var(--color-text,#1e293b);font-size:13px;' +
            'font-family:ui-monospace,monospace;width:130px;outline:none;">' +
          '<button id="wm-switch" class="btn btn-secondary btn-sm" title="Preview this version (reverts on login/logout)">Switch</button>' +
          '<button id="wm-pin" class="btn btn-primary btn-sm" title="Pin this version as your default">\\u{1F4CC} Pin</button>' +
        '</div>' +
      '</div>' +
      '<div id="wm-tags" style="display:flex;gap:6px;flex-wrap:wrap;margin:8px 0;"></div>' +
      '<div id="wm-status" style="font-size:0.8rem;min-height:18px;margin-top:4px;"></div>' +
      '<div class="settings-row" style="margin-top:4px;">' +
        '<span class="settings-label">Serving</span>' +
        '<code id="wm-cur" style="font-size:0.85rem;color:var(--color-primary,#2563eb);">' + CURRENT_REF + '</code>' +
      '</div>' +
      '<div class="settings-row" style="margin-top:2px;">' +
        '<span class="settings-label">Pinned</span>' +
        '<code id="wm-pinned" style="font-size:0.85rem;color:var(--color-success,#16a34a);">loading\\u2026</code>' +
        '<button id="wm-unpin" class="btn btn-secondary btn-sm" style="font-size:11px;padding:2px 8px;margin-left:6px;display:none;" title="Unpin (revert to main)">Unpin</button>' +
      '</div>' +
      '<p style="font-size:0.75rem;color:var(--color-text-muted,#94a3b8);margin:8px 0 0;">' +
        '<b>Switch</b> = temporary preview (reverts on sign-out). ' +
        '<b>Pin</b> = your default version (saved to Google Drive, persists across sessions and devices).</p>';

    footer.parentNode.insertBefore(s, footer);
    wireUp();
    fetchInfo();
  }

  function wireUp() {
    var input   = document.getElementById('wm-ref');
    var switchB = document.getElementById('wm-switch');
    var pinB    = document.getElementById('wm-pin');
    var unpinB  = document.getElementById('wm-unpin');
    var status  = document.getElementById('wm-status');
    var cur     = document.getElementById('wm-cur');
    var pinned  = document.getElementById('wm-pinned');
    if (!input || !switchB || !pinB) return;

    function msg(txt, color) { status.style.color = color; status.textContent = txt; }

    function doSwitch() {
      var ref = (input.value || '').trim();
      if (!ref) { msg('Enter a branch, tag, or SHA', 'var(--color-error,#dc2626)'); return; }
      msg('Switching\\u2026', 'var(--color-primary,#2563eb)');
      switchB.disabled = pinB.disabled = true;
      fetch(BASE + '/api/source/ref', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ref: ref })
      }).then(function(r) {
        if (!r.ok) return r.json().then(function(e) { throw new Error(e.error || 'Failed'); });
        return r.json();
      }).then(function(d) {
        cur.textContent = d.ref;
        try { localStorage.setItem('waymark_github_ref', JSON.stringify(d.ref)); } catch(e) {}
        // Mark session as synced so boot-time sync doesn't revert this temporary switch
        try { sessionStorage.setItem('waymark_ref_synced', '1'); } catch(e) {}
        msg('Switched to ' + d.ref + ' (preview) \\u2014 reloading\\u2026', 'var(--color-success,#16a34a)');
        setTimeout(function() { window.location.reload(); }, 600);
      }).catch(function(e) {
        msg('Error: ' + e.message, 'var(--color-error,#dc2626)');
      }).finally(function() { switchB.disabled = pinB.disabled = false; });
    }

    function doPin() {
      var ref = (input.value || '').trim();
      if (!ref) { msg('Enter a branch, tag, or SHA', 'var(--color-error,#dc2626)'); return; }
      msg('Pinning\\u2026', 'var(--color-primary,#2563eb)');
      switchB.disabled = pinB.disabled = true;
      fetch(BASE + '/api/source/pin', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ref: ref })
      }).then(function(r) {
        if (!r.ok) return r.json().then(function(e) { throw new Error(e.error || 'Failed'); });
        return r.json();
      }).then(function(d) {
        cur.textContent = d.ref;
        pinned.textContent = d.pinnedRef;
        try { localStorage.setItem('waymark_github_ref', JSON.stringify(d.ref)); } catch(e) {}
        // Save pinned ref to Google Drive for cross-device persistence.
        // The cookie (set by /api/source/pin) is a server-readable cache;
        // Drive is the source of truth.
        var saveFn = window.__waymarkSavePinnedRef;
        return (saveFn ? saveFn(d.pinnedRef) : Promise.resolve()).then(function() {
          // Clear session flag — pinned ref matches Drive, boot sync is safe
          try { sessionStorage.removeItem('waymark_ref_synced'); } catch(e) {}
          msg('\\u{1F4CC} Pinned to ' + d.pinnedRef + ' \\u2014 reloading\\u2026', 'var(--color-success,#16a34a)');
          setTimeout(function() { window.location.reload(); }, 600);
        });
      }).catch(function(e) {
        msg('Error: ' + e.message, 'var(--color-error,#dc2626)');
      }).finally(function() { switchB.disabled = pinB.disabled = false; });
    }

    function doUnpin() {
      input.value = 'main';
      doPin();
    }

    switchB.onclick = doSwitch;
    pinB.onclick = doPin;
    unpinB.onclick = doUnpin;
    input.onkeydown = function(e) { if (e.key === 'Enter') doSwitch(); };
  }

  function fetchInfo() {
    var tags   = document.getElementById('wm-tags');
    var input  = document.getElementById('wm-ref');
    var cur    = document.getElementById('wm-cur');
    var pinned = document.getElementById('wm-pinned');
    var unpinB = document.getElementById('wm-unpin');
    if (!tags) return;

    fetch(BASE + '/api/source').then(function(r) { return r.json(); }).then(function(d) {
      if (cur) cur.textContent = d.ref;
      if (pinned) pinned.textContent = d.pinnedRef || 'main';
      // Show unpin button if pinned to something other than main
      if (unpinB && d.pinnedRef && d.pinnedRef !== 'main') unpinB.style.display = '';
      else if (unpinB) unpinB.style.display = 'none';

      tags.innerHTML = '';
      var refs = d.cachedRefs || ['main'];
      if (refs.indexOf('main') === -1) refs.unshift('main');

      function normaliseRef(r) {
        if (!r || typeof r !== 'string') return r;
        if (r.indexOf('/') !== -1) return r;
        var m = r.match(/^(feature|fix|bugfix|hotfix|chore|docs|refactor|test|perf|ci|build|release)_(.+)$/i);
        if (m) return m[1] + '/' + m[2];
        return r;
      }

      var seen = {};
      refs.forEach(function(rawRef) {
        var r = normaliseRef(rawRef);
        if (!r || r.charAt(0) === '.' || seen[r]) return;
        seen[r] = true;
        var btn = document.createElement('button');
        btn.textContent = r;
        btn.className = 'btn btn-secondary btn-sm';
        var isActive = r === d.ref;
        var isPinned = r === d.pinnedRef;
        btn.style.cssText = 'font-size:12px;padding:3px 10px;border-radius:12px;' +
          (isActive ? 'border-color:var(--color-primary,#2563eb);color:var(--color-primary,#2563eb);font-weight:600;' : '') +
          (isPinned ? 'box-shadow:0 0 0 2px var(--color-success,#16a34a);' : '');
        btn.title = (isActive ? 'Currently serving' : 'Click to switch') +
          (isPinned ? ' (pinned)' : '');
        btn.onclick = function() { input.value = r; document.getElementById('wm-switch').click(); };
        tags.appendChild(btn);
      });
    }).catch(function() {});
  }
})();
</script>`;
}

/* ---------- Local-only mode ---------- */

if (config.WAYMARK_LOCAL) {
  console.log('🔧  WAYMARK_LOCAL=true — running in local-only mock mode');

  // Serve test fixtures at /__fixtures
  const fixturesDir = path.join(__dirname, '..', 'tests', 'fixtures');
  router.use('/__fixtures', express.static(fixturesDir));
}

// Serve index.html with injected __WAYMARK_BASE / __WAYMARK_LOCAL flags
// Must come before express.static so the root '/' is handled here.
router.get('/', serveIndex);

/* ---------- Scraping proxy (fetch a URL on behalf of the browser) ---------- */

router.post('/api/fetch-url', async (req, res) => {
  const { url } = req.body || {};
  if (!url || typeof url !== 'string') {
    return res.status(400).json({ error: 'Missing or invalid "url" parameter' });
  }

  let parsed;
  try { parsed = new URL(url); } catch {
    return res.status(400).json({ error: 'Invalid URL' });
  }
  if (!['http:', 'https:'].includes(parsed.protocol)) {
    return res.status(400).json({ error: 'Only HTTP/HTTPS URLs are supported' });
  }

  // Block private/internal IPs (SSRF prevention)
  function isPrivateHost(h) {
    h = h.toLowerCase();
    return (
      h === 'localhost' || h === '127.0.0.1' || h === '::1' ||
      h.startsWith('10.') || h.startsWith('192.168.') ||
      h.startsWith('172.') || h.endsWith('.local') ||
      h === '0.0.0.0' || h === '[::]' || h.startsWith('169.254.')
    );
  }

  if (isPrivateHost(parsed.hostname)) {
    return res.status(400).json({ error: 'Cannot fetch internal/private URLs' });
  }

  const MAX_RESPONSE_BYTES = 5 * 1024 * 1024; // 5 MB cap

  /** Collect response body with size limit */
  function collectBody(response) {
    return new Promise((resolve, reject) => {
      const chunks = [];
      let bytes = 0;
      response.on('data', (chunk) => {
        bytes += chunk.length;
        if (bytes > MAX_RESPONSE_BYTES) {
          response.destroy();
          return reject(new Error('Response too large (max 5 MB)'));
        }
        chunks.push(chunk);
      });
      response.on('end', () => resolve(Buffer.concat(chunks).toString('utf-8')));
      response.on('error', reject);
    });
  }

  const httpMod = parsed.protocol === 'https:' ? require('https') : require('http');

  try {
    const html = await new Promise((resolve, reject) => {
      const opts = {
        headers: {
          'User-Agent': 'Mozilla/5.0 (compatible; WayMark/1.0; +https://swiftirons.com)',
          'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        },
        timeout: 15000,
      };

      const request = httpMod.get(url, opts, (response) => {
        // Follow one redirect (re-check SSRF on redirect target)
        if ([301, 302, 303, 307, 308].includes(response.statusCode) && response.headers.location) {
          let nextUrl;
          try { nextUrl = new URL(response.headers.location, url); } catch {
            return reject(new Error('Invalid redirect URL'));
          }
          if (isPrivateHost(nextUrl.hostname)) {
            return reject(new Error('Redirect to internal/private URL blocked'));
          }
          const nextMod = nextUrl.protocol === 'https:' ? require('https') : require('http');
          nextMod.get(nextUrl.href, opts, (r2) => {
            if (r2.statusCode < 200 || r2.statusCode >= 400) return reject(new Error(`HTTP ${r2.statusCode}`));
            collectBody(r2).then(resolve, reject);
          }).on('error', reject);
          return;
        }
        if (response.statusCode < 200 || response.statusCode >= 400) {
          return reject(new Error(`HTTP ${response.statusCode}`));
        }
        collectBody(response).then(resolve, reject);
      });
      request.on('error', reject);
      request.on('timeout', () => { request.destroy(); reject(new Error('Request timed out')); });
    });

    if (!html || html.length < 100) {
      return res.status(502).json({ error: 'Empty or too-short response from target URL' });
    }
    res.json({ html });
  } catch (err) {
    res.status(502).json({ error: `Failed to fetch URL: ${err.message}` });
  }
});

/* ---------- GitHub source: admin API ---------- */

{
  /** Read the pinned ref from a signed cookie (defaults to 'main'). */
  function getPinnedRef(req) {
    return req.signedCookies?.waymark_pinned_ref || 'main';
  }

  /** Cookie options for the pinned ref (1 year, path root). */
  const PIN_COOKIE_OPTS = {
    httpOnly: true,            // no frontend code reads this cookie directly
    signed: true,
    secure: config.NODE_ENV === 'production',
    sameSite: config.NODE_ENV === 'production' ? 'strict' : 'lax',
    path: (config.BASE_PATH || '') + '/',
    maxAge: 365 * 24 * 60 * 60 * 1000,  // 1 year
  };

  /** Cookie options for the per-user temporary session ref (session-scoped, no maxAge). */
  const SESSION_REF_COOKIE_OPTS = {
    httpOnly: true,
    signed: true,
    secure: config.NODE_ENV === 'production',
    sameSite: config.NODE_ENV === 'production' ? 'strict' : 'lax',
    path: (config.BASE_PATH || '') + '/',
    // No maxAge — browser-session cookie so it is cleared when the browser closes.
  };

  // GET /api/source — current ref for THIS user + pinned ref + cached refs
  router.get('/api/source', (req, res) => {
    res.json({
      mode: 'github',
      owner: config.GITHUB_OWNER,
      repo: config.GITHUB_REPO,
      ref: getRefForRequest(req),
      pinnedRef: getPinnedRef(req),
      cachedRefs: githubSource.listCachedRefs(),
    });
  });

  // POST /api/source/ref — temporary per-user preview switch.
  // Pre-warms the ref on disk, then sets a signed session cookie so
  // ONLY this user is served the new ref.  All other users are unaffected.
  router.post('/api/source/ref', async (req, res) => {
    const { ref } = req.body || {};
    if (!ref || typeof ref !== 'string') {
      return res.status(400).json({ error: 'Missing "ref" (commit SHA, branch, or tag)' });
    }
    const trimmed = ref.trim();
    try {
      await githubSource.setRef(trimmed); // pre-warm only — no global state change
      res.cookie('waymark_session_ref', trimmed, SESSION_REF_COOKIE_OPTS);
      res.json({ ref: trimmed, pinnedRef: getPinnedRef(req) });
    } catch (err) {
      res.status(400).json({ error: err.message });
    }
  });

  // POST /api/source/pin — persist a ref as this user's default.
  // Pre-warms the ref, sets waymark_pinned_ref cookie, and clears the
  // temporary session ref so the pinned ref governs future requests.
  router.post('/api/source/pin', async (req, res) => {
    const { ref } = req.body || {};
    if (!ref || typeof ref !== 'string') {
      return res.status(400).json({ error: 'Missing "ref"' });
    }
    const trimmed = ref.trim();
    try {
      await githubSource.setRef(trimmed); // pre-warm only — no global state change
      res.cookie('waymark_pinned_ref', trimmed, PIN_COOKIE_OPTS);
      // Clear the temporary session ref — pinned ref is now the source of truth.
      res.clearCookie('waymark_session_ref', { path: (config.BASE_PATH || '') + '/' });
      res.json({ ref: trimmed, pinnedRef: trimmed, pinned: true });
    } catch (err) {
      res.status(400).json({ error: err.message });
    }
  });

  // POST /api/source/purge — clear cache for current ref
  router.post('/api/source/purge', (_req, res) => {
    githubSource.purgeCache();
    res.json({ purged: true, ref: githubSource.getRef() });
  });
}

/* ---------- Auth routes ---------- */

// Expose githubSource on the Express app so auth.js can access it on
// login/logout to restore/revert the user's pinned ref.
app.set('githubSource', githubSource);

setupAuth(router);

/* ---------- Static files ---------- */

// GitHub source middleware — serves files from the local git checkout.
// Misses fall through to the local public/ directory as a safety net.
router.use(githubSource.middleware);

// index: false — prevent express.static from serving raw index.html;
// the serveIndex handler above (and the SPA fallback below) inject runtime
// config (e.g. __WAYMARK_BASE) that the client JS needs.
router.use(express.static(path.join(__dirname, '..', 'public'), {
  index: false,
  etag: true,
  lastModified: true,
  setHeaders(res, filePath) {
    if (filePath.endsWith('.html')) {
      // HTML: always revalidate
      res.setHeader('Cache-Control', 'no-cache, must-revalidate');
    } else if (filePath.endsWith('.css') || filePath.endsWith('.js') || filePath.endsWith('.mjs')) {
      // CSS/JS/MJS: always revalidate via ETag — instant updates on mobile
      res.setHeader('Cache-Control', 'no-cache, must-revalidate');
    } else {
      // Everything else (images, SVGs, etc.): 1 hour
      res.setHeader('Cache-Control', 'public, max-age=3600');
    }
  },
}));

// SPA fallback — serve index.html for any unmatched route
router.get('*', (req, res) => {
  if (req.path.startsWith('/auth') || req.path.startsWith('/__fixtures')) {
    return res.status(404).end();
  }
  serveIndex(req, res);
});

/* ---------- Mount router at BASE_PATH ---------- */

if (basePath) {
  app.use(basePath, router);
  // Redirect /waymark → /waymark/ for clean URLs
  app.get(basePath, (_req, res) => res.redirect(301, basePath + '/'));
} else {
  app.use('/', router);
}

/* ---------- Start ---------- */

app.listen(config.PORT, async () => {
  console.log(`✅  WayMark server listening on http://localhost:${config.PORT}${basePath || '/'}`);

  // Pre-warm the GitHub file tree in the background
  await githubSource.preWarm();
});

module.exports = app; // for testing
