const path = require('path');
const fs = require('fs');
const express = require('express');
const cookieParser = require('cookie-parser');
const config = require('./config');
const setupAuth = require('./auth');
const { createGitHubSource } = require('./github-source');

const app = express();

/* ---------- Git hash + repo URL (baked at build time) ---------- */
// Generated by `node scripts/build-info.js` before `docker build`.
// Falls back to live git commands for local dev when no build-info.json exists.
let gitHash = '';
let gitRepoUrl = '';
try {
  const info = JSON.parse(fs.readFileSync(path.join(__dirname, 'build-info.json'), 'utf-8'));
  gitHash = info.hash || '';
  gitRepoUrl = info.repo || '';
} catch {
  // No build-info.json — try live git (works in dev, not in Docker)
  try {
    const { execSync } = require('child_process');
    gitHash = execSync('git rev-parse --short HEAD', { cwd: __dirname }).toString().trim();
    const remote = execSync('git remote get-url origin', { cwd: __dirname }).toString().trim();
    gitRepoUrl = remote.replace(/^git@github\.com:/, 'https://github.com/').replace(/\.git$/, '');
  } catch { /* not a git repo — hash stays empty */ }
}

/* ---------- Base-path aware router ---------- */
// When BASE_PATH is set (e.g. '/waymark'), all routes are mounted under
// that prefix so the app can live behind an nginx location block.
const basePath = config.BASE_PATH || '';
const router = express.Router();

/* ---------- Top-level middleware (runs before router) ---------- */

app.use(cookieParser(config.COOKIE_SECRET));
app.use(express.json());

// Security headers
app.use((_req, res, next) => {
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('X-Frame-Options', 'DENY');
  res.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin');

  if (config.NODE_ENV === 'production') {
    res.setHeader(
      'Content-Security-Policy',
      [
        "default-src 'self'",
        "script-src 'self' 'unsafe-inline' https://static.cloudflareinsights.com",
        "connect-src 'self' https://www.googleapis.com https://sheets.googleapis.com https://oauth2.googleapis.com",
        "img-src 'self' https://*.googleusercontent.com data:",
        "style-src 'self' 'unsafe-inline'",
      ].join('; ')
    );
  }

  next();
});

/* ---------- GitHub source setup ---------- */
// In production: clone the repo and serve files from a local git checkout.
// In WAYMARK_LOCAL mode: skip the clone, serve from local public/ only.

let githubSource;
if (config.WAYMARK_LOCAL) {
  // Stub — tests serve from the local public/ directory
  githubSource = {
    middleware: (_req, _res, next) => next(),
    setRef() {},
    getRef() { return config.GITHUB_REF; },
    preWarm() {},
    purgeCache() {},
    listCachedRefs() { return []; },
    readFile() { return null; },
  };
} else {
  githubSource = createGitHubSource({
    owner: config.GITHUB_OWNER,
    repo: config.GITHUB_REPO,
    ref: config.GITHUB_REF,
    token: config.GITHUB_TOKEN || undefined,
  });
  console.log(`📦  GitHub source: ${config.GITHUB_OWNER}/${config.GITHUB_REPO}@${config.GITHUB_REF} (local files as fallback)`);
}

/* ---------- Helper: serve index.html with injections ---------- */

function serveIndex(_req, res) {
  // Read index.html from the git checkout, fall back to local file
  let html = githubSource.readFile('index.html');
  if (!html) {
    const htmlPath = path.join(__dirname, '..', 'public', 'index.html');
    html = fs.readFileSync(htmlPath, 'utf-8');
  }

  // Inject the base path so client-side JS can build correct URLs
  const injections = [];
  if (basePath) {
    injections.push(`window.__WAYMARK_BASE='${basePath}';`);
  }
  if (config.WAYMARK_LOCAL) {
    injections.push('window.__WAYMARK_LOCAL=true;');
  }
  if (gitHash) {
    injections.push(`window.__WAYMARK_HASH='${gitHash}';`);
  }
  if (gitRepoUrl) {
    injections.push(`window.__WAYMARK_REPO='${gitRepoUrl}';`);
  }
  if (!config.WAYMARK_LOCAL) {
    injections.push(`window.__WAYMARK_GITHUB_REF='${githubSource.getRef()}';`);
    injections.push(`window.__WAYMARK_GITHUB_SOURCE=true;`);
  }
  if (injections.length) {
    html = html.replace('</head>', `  <script>${injections.join('')}</script>\n</head>`);
  }

  // In production mode, inject a settings-panel version switcher.
  // This script watches for the settings modal to open and inserts a
  // version section if the frontend code doesn't already provide one.
  // It also updates localStorage so the boot-time ref sync in app.js
  // doesn't revert the change.
  if (!config.WAYMARK_LOCAL) {
    const currentRef = githubSource.getRef();
    html = html.replace('</body>', `${buildSettingsRefInjector(currentRef)}\n</body>`);
  }

  res.setHeader('Cache-Control', 'no-cache, must-revalidate');
  res.type('html').send(html);
}

/* ---------- Server-injected settings version section ---------- */

/**
 * Build a self-contained script that injects a version-switching section
 * into the settings modal.  Works on any frontend version — old branches
 * that lack the native #settings-version-section get a dynamically created
 * one.  New branches that already have it are left untouched.
 *
 * Critically, this also updates localStorage('waymark_github_ref') so that
 * the boot-time ref sync in app.js doesn't fight the user's choice.
 */
function buildSettingsRefInjector(currentRef) {
  return `
<script>
(function() {
  var BASE = window.__WAYMARK_BASE || '';
  var CURRENT_REF = '${currentRef}';

  // Watch for the settings modal to become visible, then inject if needed.
  var obs = new MutationObserver(function() {
    var modal = document.getElementById('settings-modal');
    if (!modal || modal.classList.contains('hidden')) return;

    // If the frontend already has #settings-version-section and it's NOT hidden,
    // the native picker is handling it — do nothing.
    var existing = document.getElementById('settings-version-section');
    if (existing && !existing.classList.contains('hidden')) return;

    // Inject our version section (or un-hide + populate the existing hidden one).
    injectVersionSection(modal, existing);
  });
  obs.observe(document.body, { attributes: true, subtree: true, attributeFilter: ['class'] });

  function injectVersionSection(modal, existing) {
    // If there's an existing hidden section, populate it and show it.
    if (existing) {
      existing.classList.remove('hidden');
      populateExistingSection();
      return;
    }

    // Build a new section and insert before the modal footer.
    var footer = modal.querySelector('.modal-footer');
    if (!footer) return;

    var section = document.createElement('div');
    section.id = 'wm-injected-version';
    section.className = 'settings-section';
    section.innerHTML =
      '<h4 class="settings-section-title">App Version</h4>' +
      '<p style="font-size:0.8rem;color:var(--color-text-muted,#94a3b8);margin:0 0 12px;">Pin to a specific branch, tag, or commit.</p>' +
      '<div class="settings-row">' +
        '<span class="settings-label">Branch / Version</span>' +
        '<div style="display:flex;gap:6px;align-items:center;">' +
          '<input id="wm-inj-ref-input" type="text" value="' + CURRENT_REF + '" ' +
            'placeholder="main" autocomplete="off" spellcheck="false" ' +
            'style="padding:6px 10px;border-radius:6px;border:1px solid var(--color-border,#334155);' +
            'background:var(--color-bg,#0f172a);color:var(--color-text,#e2e8f0);font-size:13px;' +
            'font-family:monospace;width:140px;outline:none;">' +
          '<button id="wm-inj-ref-apply" class="btn btn-primary btn-sm">Apply</button>' +
        '</div>' +
      '</div>' +
      '<div style="display:flex;gap:6px;flex-wrap:wrap;margin:8px 0;" id="wm-inj-tags"></div>' +
      '<div id="wm-inj-status" style="font-size:0.8rem;min-height:18px;margin-top:4px;"></div>' +
      '<div class="settings-row" style="margin-top:8px;">' +
        '<span class="settings-label">Currently serving</span>' +
        '<code id="wm-inj-current" style="font-size:0.85rem;color:var(--color-primary,#60a5fa);">' +
          CURRENT_REF + '</code>' +
      '</div>';

    footer.parentNode.insertBefore(section, footer);
    wireUp();
    fetchInfo();
  }

  function populateExistingSection() {
    // The existing section is the native one — its JS in app.js handles it.
    // But if the frontend is an old version with a hidden section that app.js
    // never un-hides (missing __WAYMARK_GITHUB_SOURCE check), we do it and
    // the native JS will re-populate when settings opens.  Fetch info to update.
    var input = document.getElementById('settings-github-ref');
    if (input) input.value = CURRENT_REF;
    var cur = document.getElementById('settings-current-ref');
    if (cur) cur.textContent = CURRENT_REF;
  }

  function wireUp() {
    var input = document.getElementById('wm-inj-ref-input');
    var apply = document.getElementById('wm-inj-ref-apply');
    var status = document.getElementById('wm-inj-status');
    var current = document.getElementById('wm-inj-current');
    if (!input || !apply) return;

    function showStatus(msg, color) {
      status.style.color = color;
      status.textContent = msg;
    }

    function doApply() {
      var ref = (input.value || '').trim();
      if (!ref) { showStatus('Enter a branch, tag, or SHA', 'var(--color-error,#f87171)'); return; }
      showStatus('Switching\\u2026', 'var(--color-primary,#60a5fa)');
      apply.disabled = true;
      fetch(BASE + '/api/source/ref', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ref: ref })
      }).then(function(r) {
        if (!r.ok) return r.json().then(function(e) { throw new Error(e.error || 'Failed'); });
        return r.json();
      }).then(function(d) {
        current.textContent = d.ref;
        // Update localStorage so boot-time sync doesn't revert
        try { localStorage.setItem('waymark_github_ref', JSON.stringify(d.ref)); } catch(e) {}
        showStatus('Switched to ' + d.ref + ' \\u2014 reloading\\u2026', 'var(--color-success,#4ade80)');
        setTimeout(function() { window.location.reload(); }, 800);
      }).catch(function(e) {
        showStatus('Failed: ' + e.message, 'var(--color-error,#f87171)');
      }).finally(function() {
        apply.disabled = false;
      });
    }

    apply.onclick = doApply;
    input.onkeydown = function(e) { if (e.key === 'Enter') doApply(); };
  }

  function fetchInfo() {
    var tags = document.getElementById('wm-inj-tags');
    if (!tags) return;
    var input = document.getElementById('wm-inj-ref-input');
    var current = document.getElementById('wm-inj-current');

    fetch(BASE + '/api/source').then(function(r) { return r.json(); }).then(function(d) {
      if (current) current.textContent = d.ref;
      tags.innerHTML = '';
      var refs = d.cachedRefs || ['main'];
      if (!refs.includes('main')) refs.unshift('main');
      refs.forEach(function(r) {
        if (r.startsWith('.')) return;
        var btn = document.createElement('button');
        btn.textContent = r;
        btn.className = 'btn btn-secondary btn-sm';
        btn.style.cssText = 'font-size:12px;padding:3px 10px;border-radius:12px;' +
          (r === d.ref ? 'border-color:var(--color-primary,#2563eb);color:var(--color-primary,#60a5fa);' : '');
        btn.onclick = function() {
          if (input) input.value = r;
          var apply = document.getElementById('wm-inj-ref-apply');
          if (apply) apply.click();
        };
        tags.appendChild(btn);
      });
    }).catch(function() {});
  }
})();
</script>`;
}

/* ---------- Local-only mode ---------- */

if (config.WAYMARK_LOCAL) {
  console.log('🔧  WAYMARK_LOCAL=true — running in local-only mock mode');

  // Serve test fixtures at /__fixtures
  const fixturesDir = path.join(__dirname, '..', 'tests', 'fixtures');
  router.use('/__fixtures', express.static(fixturesDir));
}

// Serve index.html with injected __WAYMARK_BASE / __WAYMARK_LOCAL flags
// Must come before express.static so the root '/' is handled here.
router.get('/', serveIndex);

/* ---------- Scraping proxy (fetch a URL on behalf of the browser) ---------- */

router.post('/api/fetch-url', async (req, res) => {
  const { url } = req.body || {};
  if (!url || typeof url !== 'string') {
    return res.status(400).json({ error: 'Missing or invalid "url" parameter' });
  }

  let parsed;
  try { parsed = new URL(url); } catch {
    return res.status(400).json({ error: 'Invalid URL' });
  }
  if (!['http:', 'https:'].includes(parsed.protocol)) {
    return res.status(400).json({ error: 'Only HTTP/HTTPS URLs are supported' });
  }

  // Block private/internal IPs (SSRF prevention)
  function isPrivateHost(h) {
    h = h.toLowerCase();
    return (
      h === 'localhost' || h === '127.0.0.1' || h === '::1' ||
      h.startsWith('10.') || h.startsWith('192.168.') ||
      h.startsWith('172.') || h.endsWith('.local') ||
      h === '0.0.0.0' || h === '[::]' || h.startsWith('169.254.')
    );
  }

  if (isPrivateHost(parsed.hostname)) {
    return res.status(400).json({ error: 'Cannot fetch internal/private URLs' });
  }

  const MAX_RESPONSE_BYTES = 5 * 1024 * 1024; // 5 MB cap

  /** Collect response body with size limit */
  function collectBody(response) {
    return new Promise((resolve, reject) => {
      const chunks = [];
      let bytes = 0;
      response.on('data', (chunk) => {
        bytes += chunk.length;
        if (bytes > MAX_RESPONSE_BYTES) {
          response.destroy();
          return reject(new Error('Response too large (max 5 MB)'));
        }
        chunks.push(chunk);
      });
      response.on('end', () => resolve(Buffer.concat(chunks).toString('utf-8')));
      response.on('error', reject);
    });
  }

  const httpMod = parsed.protocol === 'https:' ? require('https') : require('http');

  try {
    const html = await new Promise((resolve, reject) => {
      const opts = {
        headers: {
          'User-Agent': 'Mozilla/5.0 (compatible; WayMark/1.0; +https://swiftirons.com)',
          'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        },
        timeout: 15000,
      };

      const request = httpMod.get(url, opts, (response) => {
        // Follow one redirect (re-check SSRF on redirect target)
        if ([301, 302, 303, 307, 308].includes(response.statusCode) && response.headers.location) {
          let nextUrl;
          try { nextUrl = new URL(response.headers.location, url); } catch {
            return reject(new Error('Invalid redirect URL'));
          }
          if (isPrivateHost(nextUrl.hostname)) {
            return reject(new Error('Redirect to internal/private URL blocked'));
          }
          const nextMod = nextUrl.protocol === 'https:' ? require('https') : require('http');
          nextMod.get(nextUrl.href, opts, (r2) => {
            if (r2.statusCode < 200 || r2.statusCode >= 400) return reject(new Error(`HTTP ${r2.statusCode}`));
            collectBody(r2).then(resolve, reject);
          }).on('error', reject);
          return;
        }
        if (response.statusCode < 200 || response.statusCode >= 400) {
          return reject(new Error(`HTTP ${response.statusCode}`));
        }
        collectBody(response).then(resolve, reject);
      });
      request.on('error', reject);
      request.on('timeout', () => { request.destroy(); reject(new Error('Request timed out')); });
    });

    if (!html || html.length < 100) {
      return res.status(502).json({ error: 'Empty or too-short response from target URL' });
    }
    res.json({ html });
  } catch (err) {
    res.status(502).json({ error: `Failed to fetch URL: ${err.message}` });
  }
});

/* ---------- GitHub source: admin API ---------- */

{
  // Auth guard — require a valid refresh token cookie for write operations
  function requireAuth(req, res, next) {
    const token = req.signedCookies?.waymark_refresh;
    if (!token) return res.status(401).json({ error: 'Authentication required' });
    next();
  }

  // GET /api/source — current ref + cached refs (read-only, no auth needed)
  router.get('/api/source', (_req, res) => {
    res.json({
      mode: 'github',
      owner: config.GITHUB_OWNER,
      repo: config.GITHUB_REPO,
      ref: githubSource.getRef(),
      cachedRefs: githubSource.listCachedRefs(),
    });
  });

  // POST /api/source/ref — switch to a different ref (no auth — public repo)
  router.post('/api/source/ref', async (req, res) => {
    const { ref } = req.body || {};
    if (!ref || typeof ref !== 'string') {
      return res.status(400).json({ error: 'Missing "ref" (commit SHA, branch, or tag)' });
    }
    try {
      await githubSource.setRef(ref.trim());
      res.json({ ref: githubSource.getRef() });
    } catch (err) {
      res.status(400).json({ error: err.message });
    }
  });

  // POST /api/source/purge — clear cache for current ref (auth required)
  router.post('/api/source/purge', requireAuth, (_req, res) => {
    githubSource.purgeCache();
    res.json({ purged: true, ref: githubSource.getRef() });
  });
}

/* ---------- Auth routes ---------- */

setupAuth(router);

/* ---------- Static files ---------- */

// GitHub source middleware — serves files from the local git checkout.
// Misses fall through to the local public/ directory as a safety net.
router.use(githubSource.middleware);

// index: false — prevent express.static from serving raw index.html;
// the serveIndex handler above (and the SPA fallback below) inject runtime
// config (e.g. __WAYMARK_BASE) that the client JS needs.
router.use(express.static(path.join(__dirname, '..', 'public'), {
  index: false,
  etag: true,
  lastModified: true,
  setHeaders(res, filePath) {
    if (filePath.endsWith('.html')) {
      // HTML: always revalidate
      res.setHeader('Cache-Control', 'no-cache, must-revalidate');
    } else if (filePath.endsWith('.css') || filePath.endsWith('.js')) {
      // CSS/JS: short cache so updates land quickly
      res.setHeader('Cache-Control', 'public, max-age=300');
    } else {
      // Everything else (images, SVGs, etc.): 1 hour
      res.setHeader('Cache-Control', 'public, max-age=3600');
    }
  },
}));

// SPA fallback — serve index.html for any unmatched route
router.get('*', (req, res) => {
  if (req.path.startsWith('/auth') || req.path.startsWith('/__fixtures')) {
    return res.status(404).end();
  }
  serveIndex(req, res);
});

/* ---------- Mount router at BASE_PATH ---------- */

if (basePath) {
  app.use(basePath, router);
  // Redirect /waymark → /waymark/ for clean URLs
  app.get(basePath, (_req, res) => res.redirect(301, basePath + '/'));
} else {
  app.use('/', router);
}

/* ---------- Start ---------- */

app.listen(config.PORT, async () => {
  console.log(`✅  WayMark server listening on http://localhost:${config.PORT}${basePath || '/'}`);

  // Pre-warm the GitHub file tree in the background
  await githubSource.preWarm();
});

module.exports = app; // for testing
