const path = require('path');
const fs = require('fs');
const express = require('express');
const cookieParser = require('cookie-parser');
const config = require('./config');
const setupAuth = require('./auth');
const { createGitHubSource } = require('./github-source');

const app = express();

/* ---------- Git hash + repo URL (baked at build time) ---------- */
// Generated by `node scripts/build-info.js` before `docker build`.
// Falls back to live git commands for local dev when no build-info.json exists.
let gitHash = '';
let gitRepoUrl = '';
try {
  const info = JSON.parse(fs.readFileSync(path.join(__dirname, 'build-info.json'), 'utf-8'));
  gitHash = info.hash || '';
  gitRepoUrl = info.repo || '';
} catch {
  // No build-info.json — try live git (works in dev, not in Docker)
  try {
    const { execSync } = require('child_process');
    gitHash = execSync('git rev-parse --short HEAD', { cwd: __dirname }).toString().trim();
    const remote = execSync('git remote get-url origin', { cwd: __dirname }).toString().trim();
    gitRepoUrl = remote.replace(/^git@github\.com:/, 'https://github.com/').replace(/\.git$/, '');
  } catch { /* not a git repo — hash stays empty */ }
}

/* ---------- Base-path aware router ---------- */
// When BASE_PATH is set (e.g. '/waymark'), all routes are mounted under
// that prefix so the app can live behind an nginx location block.
const basePath = config.BASE_PATH || '';
const router = express.Router();

/* ---------- Top-level middleware (runs before router) ---------- */

app.use(cookieParser(config.COOKIE_SECRET));
app.use(express.json());

// Security headers
app.use((_req, res, next) => {
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('X-Frame-Options', 'DENY');
  res.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin');

  if (config.NODE_ENV === 'production') {
    res.setHeader(
      'Content-Security-Policy',
      [
        "default-src 'self'",
        "script-src 'self' 'unsafe-inline' https://static.cloudflareinsights.com",
        "connect-src 'self' https://www.googleapis.com https://sheets.googleapis.com https://oauth2.googleapis.com",
        "img-src 'self' https://*.googleusercontent.com data:",
        "style-src 'self' 'unsafe-inline'",
      ].join('; ')
    );
  }

  next();
});

/* ---------- GitHub source setup ---------- */
// In production: clone the repo and serve files from a local git checkout.
// In WAYMARK_LOCAL mode: skip the clone, serve from local public/ only.

let githubSource;
if (config.WAYMARK_LOCAL) {
  // Stub — tests serve from the local public/ directory
  githubSource = {
    middleware: (_req, _res, next) => next(),
    setRef() {},
    getRef() { return config.GITHUB_REF; },
    preWarm() {},
    purgeCache() {},
    listCachedRefs() { return []; },
    readFile() { return null; },
  };
} else {
  githubSource = createGitHubSource({
    owner: config.GITHUB_OWNER,
    repo: config.GITHUB_REPO,
    ref: config.GITHUB_REF,
    token: config.GITHUB_TOKEN || undefined,
  });
  console.log(`📦  GitHub source: ${config.GITHUB_OWNER}/${config.GITHUB_REPO}@${config.GITHUB_REF} (local files as fallback)`);
}

/* ---------- Helper: serve index.html with injections ---------- */

function serveIndex(_req, res) {
  // Read index.html from the git checkout, fall back to local file
  let html = githubSource.readFile('index.html');
  if (!html) {
    const htmlPath = path.join(__dirname, '..', 'public', 'index.html');
    html = fs.readFileSync(htmlPath, 'utf-8');
  }

  // Inject the base path so client-side JS can build correct URLs
  const injections = [];
  if (basePath) {
    injections.push(`window.__WAYMARK_BASE='${basePath}';`);
  }
  if (config.WAYMARK_LOCAL) {
    injections.push('window.__WAYMARK_LOCAL=true;');
  }
  if (gitHash) {
    injections.push(`window.__WAYMARK_HASH='${gitHash}';`);
  }
  if (gitRepoUrl) {
    injections.push(`window.__WAYMARK_REPO='${gitRepoUrl}';`);
  }
  if (!config.WAYMARK_LOCAL) {
    injections.push(`window.__WAYMARK_GITHUB_REF='${githubSource.getRef()}';`);
    injections.push(`window.__WAYMARK_GITHUB_SOURCE=true;`);
  }
  if (injections.length) {
    html = html.replace('</head>', `  <script>${injections.join('')}</script>\n</head>`);
  }

  // In production mode, inject a standalone version-switcher widget.
  // This widget is fully self-contained (inline CSS + JS) so it works
  // even when the active ref is an old branch that lacks the settings
  // version picker.  Without this, switching to an old ref is a one-way
  // trip — you'd have no UI to switch back.
  if (!config.WAYMARK_LOCAL) {
    const currentRef = githubSource.getRef();
    html = html.replace('</body>', `${buildRefWidget(currentRef)}\n</body>`);
  }

  res.setHeader('Cache-Control', 'no-cache, must-revalidate');
  res.type('html').send(html);
}

/* ---------- Server-injected ref-switcher widget ---------- */

/**
 * Build a self-contained floating widget that lets the user switch refs
 * regardless of what frontend code is running.  All CSS is inline so it
 * has zero dependency on the frontend's stylesheets.
 */
function buildRefWidget(currentRef) {
  return `
<!-- Server-injected ref switcher — works on ANY frontend version -->
<div id="wm-ref-widget" style="
  position:fixed; bottom:16px; right:16px; z-index:999999;
  font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
  font-size:13px;
">
  <!-- Toggle button -->
  <button id="wm-ref-toggle" title="Switch frontend version" style="
    width:40px; height:40px; border-radius:50%; border:none; cursor:pointer;
    background:#2563eb; color:#fff; font-size:18px; line-height:40px;
    box-shadow:0 2px 8px rgba(0,0,0,0.25); display:flex; align-items:center;
    justify-content:center; transition:transform 0.2s;
  " aria-label="Switch frontend version">⚙</button>

  <!-- Panel (hidden by default) -->
  <div id="wm-ref-panel" style="
    display:none; position:absolute; bottom:52px; right:0;
    width:300px; background:#1e293b; color:#e2e8f0; border-radius:10px;
    box-shadow:0 4px 20px rgba(0,0,0,0.4); padding:16px;
  ">
    <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:12px;">
      <span style="font-weight:600; font-size:14px;">🔀 Version Switcher</span>
      <button id="wm-ref-close" style="
        background:none; border:none; color:#94a3b8; cursor:pointer;
        font-size:18px; line-height:1; padding:0;
      ">✕</button>
    </div>

    <div style="margin-bottom:10px; font-size:12px; color:#94a3b8;">
      Serving from: <strong id="wm-ref-current" style="color:#60a5fa;">${currentRef}</strong>
    </div>

    <div style="display:flex; gap:6px; margin-bottom:10px;">
      <input id="wm-ref-input" type="text" value="${currentRef}" placeholder="branch, tag, or SHA" style="
        flex:1; padding:7px 10px; border-radius:6px; border:1px solid #334155;
        background:#0f172a; color:#e2e8f0; font-size:13px; font-family:monospace;
        outline:none;
      ">
      <button id="wm-ref-apply" style="
        padding:7px 14px; border-radius:6px; border:none; cursor:pointer;
        background:#2563eb; color:#fff; font-size:13px; font-weight:500;
        white-space:nowrap;
      ">Apply</button>
    </div>

    <div style="display:flex; gap:6px; flex-wrap:wrap; margin-bottom:10px;">
      <button class="wm-ref-tag" data-ref="main" style="
        padding:4px 10px; border-radius:12px; border:1px solid #334155;
        background:transparent; color:#94a3b8; cursor:pointer; font-size:12px;
      ">main</button>
    </div>

    <div id="wm-ref-status" style="
      font-size:12px; min-height:18px; margin-top:4px;
    "></div>
  </div>
</div>

<script>
(function() {
  var toggle = document.getElementById('wm-ref-toggle');
  var panel = document.getElementById('wm-ref-panel');
  var close = document.getElementById('wm-ref-close');
  var input = document.getElementById('wm-ref-input');
  var apply = document.getElementById('wm-ref-apply');
  var status = document.getElementById('wm-ref-status');
  var current = document.getElementById('wm-ref-current');
  var base = window.__WAYMARK_BASE || '';

  toggle.onclick = function() {
    var showing = panel.style.display !== 'none';
    panel.style.display = showing ? 'none' : 'block';
    if (!showing) fetchInfo();
  };
  close.onclick = function() { panel.style.display = 'none'; };

  function showStatus(msg, type) {
    var colors = { info: '#60a5fa', success: '#4ade80', error: '#f87171' };
    status.style.color = colors[type] || '#94a3b8';
    status.textContent = msg;
  }

  function fetchInfo() {
    fetch(base + '/api/source').then(function(r) { return r.json(); }).then(function(d) {
      current.textContent = d.ref;
      // Add cached ref tags
      var container = panel.querySelector('.wm-ref-tag').parentNode;
      container.innerHTML = '';
      (d.cachedRefs || ['main']).forEach(function(ref) {
        if (ref.startsWith('.')) return;
        var btn = document.createElement('button');
        btn.className = 'wm-ref-tag';
        btn.dataset.ref = ref;
        btn.textContent = ref;
        btn.style.cssText = 'padding:4px 10px;border-radius:12px;border:1px solid ' +
          (ref === d.ref ? '#2563eb' : '#334155') + ';background:' +
          (ref === d.ref ? '#1e3a5f' : 'transparent') + ';color:' +
          (ref === d.ref ? '#60a5fa' : '#94a3b8') + ';cursor:pointer;font-size:12px;';
        btn.onclick = function() { input.value = ref; doApply(); };
        container.appendChild(btn);
      });
      // Always ensure "main" is present
      if (!(d.cachedRefs || []).includes('main')) {
        var mainBtn = document.createElement('button');
        mainBtn.className = 'wm-ref-tag';
        mainBtn.dataset.ref = 'main';
        mainBtn.textContent = 'main';
        mainBtn.style.cssText = 'padding:4px 10px;border-radius:12px;border:1px solid #334155;background:transparent;color:#94a3b8;cursor:pointer;font-size:12px;';
        mainBtn.onclick = function() { input.value = 'main'; doApply(); };
        container.insertBefore(mainBtn, container.firstChild);
      }
    }).catch(function() {});
  }

  function doApply() {
    var ref = (input.value || '').trim();
    if (!ref) { showStatus('Enter a branch, tag, or SHA', 'error'); return; }
    showStatus('Switching…', 'info');
    apply.disabled = true;
    fetch(base + '/api/source/ref', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ ref: ref })
    }).then(function(r) {
      if (!r.ok) return r.json().then(function(e) { throw new Error(e.error || 'Failed'); });
      return r.json();
    }).then(function(d) {
      current.textContent = d.ref;
      showStatus('Switched to ' + d.ref + ' — reloading…', 'success');
      setTimeout(function() { window.location.reload(); }, 800);
    }).catch(function(e) {
      showStatus('Failed: ' + e.message, 'error');
    }).finally(function() {
      apply.disabled = false;
    });
  }

  apply.onclick = doApply;
  input.onkeydown = function(e) { if (e.key === 'Enter') doApply(); };

  // If the frontend app has its own settings version picker, hide this widget
  // to avoid redundancy (the app's picker is prettier and Drive-integrated).
  var observer = new MutationObserver(function() {
    if (document.getElementById('settings-version-section')) {
      document.getElementById('wm-ref-widget').style.display = 'none';
      observer.disconnect();
    }
  });
  observer.observe(document.body, { childList: true, subtree: true });
  // Disconnect after 10s to avoid memory leaks
  setTimeout(function() { observer.disconnect(); }, 10000);
})();
</script>`;
}

/* ---------- Local-only mode ---------- */

if (config.WAYMARK_LOCAL) {
  console.log('🔧  WAYMARK_LOCAL=true — running in local-only mock mode');

  // Serve test fixtures at /__fixtures
  const fixturesDir = path.join(__dirname, '..', 'tests', 'fixtures');
  router.use('/__fixtures', express.static(fixturesDir));
}

// Serve index.html with injected __WAYMARK_BASE / __WAYMARK_LOCAL flags
// Must come before express.static so the root '/' is handled here.
router.get('/', serveIndex);

/* ---------- Scraping proxy (fetch a URL on behalf of the browser) ---------- */

router.post('/api/fetch-url', async (req, res) => {
  const { url } = req.body || {};
  if (!url || typeof url !== 'string') {
    return res.status(400).json({ error: 'Missing or invalid "url" parameter' });
  }

  let parsed;
  try { parsed = new URL(url); } catch {
    return res.status(400).json({ error: 'Invalid URL' });
  }
  if (!['http:', 'https:'].includes(parsed.protocol)) {
    return res.status(400).json({ error: 'Only HTTP/HTTPS URLs are supported' });
  }

  // Block private/internal IPs (SSRF prevention)
  function isPrivateHost(h) {
    h = h.toLowerCase();
    return (
      h === 'localhost' || h === '127.0.0.1' || h === '::1' ||
      h.startsWith('10.') || h.startsWith('192.168.') ||
      h.startsWith('172.') || h.endsWith('.local') ||
      h === '0.0.0.0' || h === '[::]' || h.startsWith('169.254.')
    );
  }

  if (isPrivateHost(parsed.hostname)) {
    return res.status(400).json({ error: 'Cannot fetch internal/private URLs' });
  }

  const MAX_RESPONSE_BYTES = 5 * 1024 * 1024; // 5 MB cap

  /** Collect response body with size limit */
  function collectBody(response) {
    return new Promise((resolve, reject) => {
      const chunks = [];
      let bytes = 0;
      response.on('data', (chunk) => {
        bytes += chunk.length;
        if (bytes > MAX_RESPONSE_BYTES) {
          response.destroy();
          return reject(new Error('Response too large (max 5 MB)'));
        }
        chunks.push(chunk);
      });
      response.on('end', () => resolve(Buffer.concat(chunks).toString('utf-8')));
      response.on('error', reject);
    });
  }

  const httpMod = parsed.protocol === 'https:' ? require('https') : require('http');

  try {
    const html = await new Promise((resolve, reject) => {
      const opts = {
        headers: {
          'User-Agent': 'Mozilla/5.0 (compatible; WayMark/1.0; +https://swiftirons.com)',
          'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        },
        timeout: 15000,
      };

      const request = httpMod.get(url, opts, (response) => {
        // Follow one redirect (re-check SSRF on redirect target)
        if ([301, 302, 303, 307, 308].includes(response.statusCode) && response.headers.location) {
          let nextUrl;
          try { nextUrl = new URL(response.headers.location, url); } catch {
            return reject(new Error('Invalid redirect URL'));
          }
          if (isPrivateHost(nextUrl.hostname)) {
            return reject(new Error('Redirect to internal/private URL blocked'));
          }
          const nextMod = nextUrl.protocol === 'https:' ? require('https') : require('http');
          nextMod.get(nextUrl.href, opts, (r2) => {
            if (r2.statusCode < 200 || r2.statusCode >= 400) return reject(new Error(`HTTP ${r2.statusCode}`));
            collectBody(r2).then(resolve, reject);
          }).on('error', reject);
          return;
        }
        if (response.statusCode < 200 || response.statusCode >= 400) {
          return reject(new Error(`HTTP ${response.statusCode}`));
        }
        collectBody(response).then(resolve, reject);
      });
      request.on('error', reject);
      request.on('timeout', () => { request.destroy(); reject(new Error('Request timed out')); });
    });

    if (!html || html.length < 100) {
      return res.status(502).json({ error: 'Empty or too-short response from target URL' });
    }
    res.json({ html });
  } catch (err) {
    res.status(502).json({ error: `Failed to fetch URL: ${err.message}` });
  }
});

/* ---------- GitHub source: admin API ---------- */

{
  // Auth guard — require a valid refresh token cookie for write operations
  function requireAuth(req, res, next) {
    const token = req.signedCookies?.waymark_refresh;
    if (!token) return res.status(401).json({ error: 'Authentication required' });
    next();
  }

  // GET /api/source — current ref + cached refs (read-only, no auth needed)
  router.get('/api/source', (_req, res) => {
    res.json({
      mode: 'github',
      owner: config.GITHUB_OWNER,
      repo: config.GITHUB_REPO,
      ref: githubSource.getRef(),
      cachedRefs: githubSource.listCachedRefs(),
    });
  });

  // POST /api/source/ref — switch to a different ref (no auth — public repo)
  router.post('/api/source/ref', async (req, res) => {
    const { ref } = req.body || {};
    if (!ref || typeof ref !== 'string') {
      return res.status(400).json({ error: 'Missing "ref" (commit SHA, branch, or tag)' });
    }
    try {
      await githubSource.setRef(ref.trim());
      res.json({ ref: githubSource.getRef() });
    } catch (err) {
      res.status(400).json({ error: err.message });
    }
  });

  // POST /api/source/purge — clear cache for current ref (auth required)
  router.post('/api/source/purge', requireAuth, (_req, res) => {
    githubSource.purgeCache();
    res.json({ purged: true, ref: githubSource.getRef() });
  });
}

/* ---------- Auth routes ---------- */

setupAuth(router);

/* ---------- Static files ---------- */

// GitHub source middleware — serves files from the local git checkout.
// Misses fall through to the local public/ directory as a safety net.
router.use(githubSource.middleware);

// index: false — prevent express.static from serving raw index.html;
// the serveIndex handler above (and the SPA fallback below) inject runtime
// config (e.g. __WAYMARK_BASE) that the client JS needs.
router.use(express.static(path.join(__dirname, '..', 'public'), {
  index: false,
  etag: true,
  lastModified: true,
  setHeaders(res, filePath) {
    if (filePath.endsWith('.html')) {
      // HTML: always revalidate
      res.setHeader('Cache-Control', 'no-cache, must-revalidate');
    } else if (filePath.endsWith('.css') || filePath.endsWith('.js')) {
      // CSS/JS: short cache so updates land quickly
      res.setHeader('Cache-Control', 'public, max-age=300');
    } else {
      // Everything else (images, SVGs, etc.): 1 hour
      res.setHeader('Cache-Control', 'public, max-age=3600');
    }
  },
}));

// SPA fallback — serve index.html for any unmatched route
router.get('*', (req, res) => {
  if (req.path.startsWith('/auth') || req.path.startsWith('/__fixtures')) {
    return res.status(404).end();
  }
  serveIndex(req, res);
});

/* ---------- Mount router at BASE_PATH ---------- */

if (basePath) {
  app.use(basePath, router);
  // Redirect /waymark → /waymark/ for clean URLs
  app.get(basePath, (_req, res) => res.redirect(301, basePath + '/'));
} else {
  app.use('/', router);
}

/* ---------- Start ---------- */

app.listen(config.PORT, async () => {
  console.log(`✅  WayMark server listening on http://localhost:${config.PORT}${basePath || '/'}`);

  // Pre-warm the GitHub file tree in the background
  await githubSource.preWarm();
});

module.exports = app; // for testing
