#!/usr/bin/env bash
# learn-repo.test.sh — Tests for workspace introspection and AI tool configuration.
#
# Verifies that learn-repo.sh correctly discovers project AI config and
# generates the right output files for each AI provider.
#
# Usage:
#   bash dev-worker/tests/learn-repo.test.sh [container-name]

set -uo pipefail

CONTAINER="${1:-waymark-dev-worker}"
source "$(dirname "$0")/lib/helpers.sh"

header "Workspace introspection and AI tool configuration"

# ── /etc/repo-context.md generated ───────────────────────────────────────────
if exec_q "test -f /etc/repo-context.md"; then
    pass "/etc/repo-context.md generated by learn-repo.sh"
    SIZE=$(exec_q "wc -c < /etc/repo-context.md" || echo "0")
    [[ "$SIZE" -gt 100 ]] && pass "  Content: ${SIZE} bytes (non-trivial)" \
                           || fail "  Content too small: ${SIZE} bytes"
else
    fail "/etc/repo-context.md not found — learn-repo.sh may have failed"
fi

# ── AI_PROVIDER resolved in /etc/agent-env.sh ────────────────────────────────
RESOLVED_PROVIDER=$(exec_q "bash -c 'source /etc/agent-env.sh 2>/dev/null; echo \$AI_PROVIDER'" || echo "")
if [[ "$RESOLVED_PROVIDER" == "copilot" || "$RESOLVED_PROVIDER" == "claude" ]]; then
    pass "AI_PROVIDER resolved: '${RESOLVED_PROVIDER}'"
else
    fail "AI_PROVIDER not resolved (got: '${RESOLVED_PROVIDER:-<empty>}')"
    echo "  Expected 'copilot' or 'claude' — learn-repo.sh must have failed"
fi

# ── MCP config discovery ──────────────────────────────────────────────────────
if exec_q "test -f /workspace/.vscode/mcp.json"; then
    pass "Source MCP config found: .vscode/mcp.json"

    # Claude format should be generated
    if exec_q "test -f /workspace/.mcp.json"; then
        pass ".mcp.json generated for Claude Code"
        KEYS=$(exec_q "node -e \"const j=require('/workspace/.mcp.json'); console.log(Object.keys(j.mcpServers||{}).join(','))\"" || echo "")
        [[ -n "$KEYS" ]] && pass "  MCP servers: ${KEYS}" \
                         || fail "  .mcp.json has no mcpServers entries"
    else
        fail ".mcp.json NOT generated — Claude Code will have no MCP tools"
    fi

    # Copilot format should be generated
    if exec_q "test -f /root/.copilot/mcp.json"; then
        pass "~/.copilot/mcp.json generated for Copilot CLI"
        KEYS=$(exec_q "node -e \"const j=require('/root/.copilot/mcp.json'); console.log(Object.keys(j.servers||{}).join(','))\"" || echo "")
        [[ -n "$KEYS" ]] && pass "  MCP servers: ${KEYS}" \
                         || fail "  ~/.copilot/mcp.json has no servers entries"
    else
        fail "~/.copilot/mcp.json NOT generated — Copilot CLI will have no MCP tools"
    fi

    # Variable substitution — no ${workspaceFolder} literals should remain
    if exec_q "grep -q '\${workspaceFolder}' /workspace/.mcp.json 2>/dev/null"; then
        fail "Variable substitution failed: \${workspaceFolder} still in .mcp.json"
    else
        pass "MCP variable substitution correct (no \${...} literals remain)"
    fi
else
    skip "No .vscode/mcp.json in workspace — MCP translation tests skipped"
fi

# ── CLAUDE.md present ─────────────────────────────────────────────────────────
if exec_q "test -f /workspace/CLAUDE.md"; then
    pass "CLAUDE.md present in workspace root"
    LINES=$(exec_q "wc -l < /workspace/CLAUDE.md" || echo "0")
    [[ "$LINES" -gt 10 ]] && pass "  Content: ${LINES} lines (non-trivial)" \
                           || fail "  CLAUDE.md is suspiciously short: ${LINES} lines"
else
    fail "CLAUDE.md not found — Claude Code has no project instructions"
fi

# ── Agent definitions discovered ──────────────────────────────────────────────
AGENT_COUNT=$(exec_q "find /workspace/.github/agents -name '*.agent.md' 2>/dev/null | wc -l" || echo "0")
if [[ "$AGENT_COUNT" -gt 0 ]]; then
    pass "${AGENT_COUNT} agent definition(s) found in .github/agents/"
    AGENT_NAMES=$(exec_q "ls /workspace/.github/agents/*.agent.md 2>/dev/null | xargs -I{} basename {} .agent.md | tr '\n' ' '" || echo "")
    pass "  Agents: ${AGENT_NAMES}"
else
    skip "No .agent.md files found — this project may not use Copilot agents"
fi

# ── Instructions discovered ────────────────────────────────────────────────────
INST_COUNT=$(exec_q "find /workspace/.github/instructions -name '*.instructions.md' 2>/dev/null | wc -l" || echo "0")
if [[ "$INST_COUNT" -gt 0 ]]; then
    pass "${INST_COUNT} instruction file(s) found in .github/instructions/"
else
    skip "No .instructions.md files found"
fi

summary
